cargo-features = ["named-profiles"]

[package]
name = "asm_test"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[profile.kernel_debug]
inherits = "dev"
opt-level = "s"

[dependencies]
